### ISSUE TITLE
helm install with nodeport service

### ISSUE THREAD

**Issue by weironz** [ansible/tower-operator#1025]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

i don' know how to install with --set options
```
helm upgrade -i awx-operator -n awx --create-namespace charts/awx-operator --set AWX.enabled=true,service_type=NodePort,projects_persistence=true
```

```
# helm upgrade -i awx-operator -n awx --create-namespace charts/awx-operator --set AWX.enabled=true,service_type=NodePort,projects_persistence=true
Release "awx-operator" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "AWX" in version "awx.ansible.com/v1beta1"
```

**Comment by fosterseth** [comment]
@willzhang were you able to resolve this? If not, please open a new topic on the mailing list here https://groups.google.com/u/1/g/awx-project

**Comment by akus062381** [comment]
Hi @willzhang!

Thank you very much for for this issue. It means a lot to us that you have taken time to contribute by opening this report.

On this issue, there were comments added but it has been some time since then without response. At this time we are closing this issue. If you get time to address the comments we can reopen the issue if you can contact us by using any of the communication methods listed in the page below:

https://github.com/ansible/awx/#get-involved

Thank you once again for this and your interest in AWX!
