### ISSUE TITLE
Project clone is failling during "fetch galaxy roles from requirements" 

### ISSUE THREAD

**Issue by RogerSik** [ansible/tower-operator#1047]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Since 2 days the "Projects" job is failling during the "fetch galaxy roles from requirements.(yml/yaml)" task

### AWX Operator version

0.28.0

### AWX version

21.5.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.23

### Modifications

no

### Steps to reproduce

* Setup a gitlab project.
* Setup galaxy roles in requierements
* do a projects sync in AWX

### Expected results

* successfull project sync

### Actual results

* It fails with the error
* 
![09_09-05-09](https://user-images.githubusercontent.com/165814/189291874-76d66dd6-58ff-48a2-8f0d-1a775ad0f1e6.png)

**Comment by royvandongen** [comment]
Can confirm, i have got the exact same behaviour (just updated to AWX 21.5).

At this moment i'm considering trying to change the default "Control Plane Execution Environment" to something else, however since i am rather new to AWX this looks like a lot of custom tinkering.

**Comment by RogerSik** [comment]
@royvandongen can you change the "Control Plane Execution Environment"? Here it is greyed out and dont allow modification. Otherwise issue is that "latest" is always up2date, other tags are multiple months old.

**Comment by royvandongen** [comment]
@RogerSik Hi, You cannot change the default CPEE, I believe this is by default. Since the last AWX update there is even an option to globally change the default EE (Miscellaneous System settings->Global default execution environment). However this is ignored totally by the CPEE. 

it would be a good idea to make this variable changeable for end users, And to provide a better maintained image.(Might not be needed if custom EE's can be selected as default).

**Comment by PaulVerhoeven1** [comment]
This could be related to the following issue: https://github.com/ansible/awx-ee/issues/134

**Comment by RogerSik** [comment]
Its work now with latest! 

But a stable image or some CI checks or the possible to go to older images which are some days / weeks instead 1 year old would be cool.

**Comment by royvandongen** [comment]
> Its work now with latest!

Unfortunatly i can not confirm this for me. I have even changed to Downloading the image before every run, but it still fails with the exact message as written above.

+1 for a stable tag!

**Comment by akus062381** [comment]
@RogerSik 

We are glad to see that you have been able to resolve your issue!

We do have the following open issue that is addressing the need for tagged ee images:
https://github.com/ansible/awx-ee/issues/125

Since this issue is resolved, we are going to close it. Please feel free to reopen if you have any further problems!
Thank you!
