### ISSUE TITLE
Docs on how to add custom AWX logo

### ISSUE THREAD

**Issue by fosterseth** [ansible/tower-operator#1066]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

Users may wish to swap out the AWX logo for their own. It would be nice to have docs (and maybe an operator change) to allow for this.

See this PR on how to change awx logo for the older docker based deployments. This approach would be need to be updated to work with k8s deployments.

https://github.com/ansible/awx/pull/12265

**Comment by fosterseth** [comment]
@shanemcd  may have docs on this

**Comment by rebeccahhh** [comment]
relevant awx docs to model after(maybe?): 
old: https://docs.ansible.com/ansible-tower/latest/html/administration/custom_rebranding.html
old: https://docs.ansible.com/ansible-tower/2.4.5/html/administration/custom_rebranding.html
latest: https://docs.ansible.com/automation-controller/latest/html/administration/custom_rebranding.html

**Comment by YaronL16** [comment]
I would like to contribute but am new to open-source and have never done so before, am I correct assuming the doc should go in '/docs/user-guide/advanced-configuration'?

**Comment by kurokobo** [comment]
@YaronL16 
Hi, welcome to the community 😃 
You are right, the new docs for this issue should be placed under `/docs/user-guide/advanced-configuration`.

The whole documentation is build by mkdocs, so in addition to place new markdown files there, adding navigation in `mkdocs.yml` is required: https://github.com/ansible/awx-operator/blob/f8bbe9f55a0d27efa4be4428523ad20ee0d418d0/mkdocs.yml#L40-L90

Please see the `README.md` under `docs` to know how to build docs locally: https://github.com/ansible/awx-operator/tree/devel/docs

**Comment by YaronL16** [comment]
Thank you @kurokobo 

Honestly after looking into it I don't think it belongs in the Operator docs, but in the regular AWX docs, as seen here:
https://ansible.readthedocs.io/projects/awx/en/latest/administration/custom_rebranding.html
I don't mind adding the page if you think it can be useful, but I don't see how it's relevant to the Operator.

**Comment by kurokobo** [comment]
@YaronL16 
Okay so let me explain why this issue is on Operator repo instead of AWX repo.

AWX has two logos; logo in the login screen, and the header logo(top-left corner on the UI). Indeed the users can change _the login logo_ via UI as you've stated, but currently there is no UI to change header logo.

But technically we can change the header logo by _overriding logo image by mounting new image on the specific path in the web pod by AWX Operator_. Also in the same way, the login logo can also be replaced without any UI work.

There is already documentation for replacing favicon in this manner: https://ansible.readthedocs.io/projects/awx-operator/en/latest/user-guide/advanced-configuration/custom-volume-and-volume-mount-options.html#custom-favicon

If you want to continue to work on this Issue, instead of adding a new page, it would be sufficient to simply add a “CUSTOM LOGOS” section to the above page. First of all you should find the paths for logos to be overridden 😃

**Comment by YaronL16** [comment]
> @YaronL16 Okay so let me explain why this issue is on Operator repo instead of AWX repo.
> 
> AWX has two logos; logo in the login screen, and the header logo(top-left corner on the UI). Indeed the users can change _the login logo_ via UI as you've stated, but currently there is no UI to change header logo.
> 
> But technically we can change the header logo by _overriding logo image by mounting new image on the specific path in the web pod by AWX Operator_. Also in the same way, the login logo can also be replaced without any UI work.
> 
> There is already documentation for replacing favicon in this manner: https://ansible.readthedocs.io/projects/awx-operator/en/latest/user-guide/advanced-configuration/custom-volume-and-volume-mount-options.html#custom-favicon
> 
> If you want to continue to work on this Issue, instead of adding a new page, it would be sufficient to simply add a “CUSTOM LOGOS” section to the above page. First of all you should find the paths for logos to be overridden 😃

Hi @kurokobo , thanks for the clarification, that cleared it up.
Just submitted PR #1840.
Please let me know if there's anything that needs changing
