### ISSUE TITLE
Add awx-operator to ArtifactHub.io?

### ISSUE THREAD

**Issue by boldandbusted** [ansible/tower-operator#1079]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

Howdy. I am a fan of ArtifactHub.io - this Linux Foundation project has really nice features to help Helm chart users and producers to find each other, and even makes parsing schemas easier (for example, I use  "Default Values" popover interface frequently as a reference when setting Chart values.)

Here's the portion of the docs that are for https://artifacthub.io/docs/topics/repositories/

Thanks for this AWX Operator! :) Cheers.

**Comment by shanemcd** [comment]
Hello! We're unlikely to do this ourselves (not a lot of extra time these days), but we're totally willing to review a PR that adds this (as long as it is automated via a GitHub Action, no hardcoded versions or requiring any manual file changes in order to release). The AWX Helm chart itself was actually a community contribution. Maybe read through the discussion on the initial Helm PR to get a sense of what'd it take to get something like this merged: https://github.com/ansible/awx-operator/pull/799

**Comment by akus062381** [comment]
Hi @boldandbusted,
Thank you very much for for this issue. It means a lot to us that you have taken time to contribute by opening this report.

On this issue, there were comments added but it has been some time since then without response. At this time we are closing this issue. If you get time to address the comments we can reopen the issue if you can contact us by using any of the communication methods listed in the page below:

https://github.com/ansible/awx/#get-involved

Thank you once again for this and your interest in AWX!

**Comment by boldandbusted** [comment]
The fact that this was a "heartfelt" robot reply somehow makes it worse than a "WONTFIX". :(
