### ISSUE TITLE
Execution node - Install_receptor.yml fails on installation of pip3.

### ISSUE THREAD

**Issue by MattMatheus** [ansible/tower-operator#1090]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

While adding execution nodes (released in 0.30.0) to AWX, installation fails while executing the installation playbook.

TASK [ansible.receptor.setup : Install dependencies specific to the node type] 
***fatal: [remote-execution]: FAILED! => {"changed": false, "failures": ["No package python39-pip available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}

This may actually be an issue with the role coming out of galaxy, but on both RHEL 8/9 and Rocky 9, this message is observed.  I believe the correct package name is python3-pip.  

A workaround exists by manually installing the needed packages using correct names and removing the task from the role.

### AWX Operator version

0.30.0

### AWX version

21.7.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.22.11

### Modifications

no

### Steps to reproduce

1. Create new execution node inside of AWX
2. Download installation package and copy to target node
3. Prep inventory file with target credentials
4. Execute playbook 'ansible-playbook -i inventory.yml install_receptor.yml'

### Expected results

Installation of the role to complete successfully.

### Actual results

Role fails on package installation with error about package name

TASK [ansible.receptor.setup : Install dependencies specific to the node type] 
***fatal: [remote-execution]: FAILED! => {"changed": false, "failures": ["No package python39-pip available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}

### Additional information

Again, this might be an issue with the receptor role, but it seemed prudent to lodge an issue with operator given the new feature released in 0.30.0

### Operator Logs

No logs were output as the error occurred on remote node installation.

**Comment by kurokobo** [comment]
Hi, I think this issue should be opened (or moved) on [ansible/awx](https://github.com/ansible/awx) repository [since the requirements for `python39-pip` for install bundle is defined on the AWX side](https://github.com/ansible/awx/blob/eeb9d6148827a8da366bf9cbb32fa96684dd4e4c/awx/api/templates/instance_install_bundle/group_vars/all.yml#L18-L19).

For [CentOS Stream 8](http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/Packages/) and [RHEL 8](https://access.redhat.com/downloads/content/python39-pip/noarch/package-latest) `python39-pip` is correct, but indeed for _9_, this should be `python3-pip` for both [CentOS Stream 9](http://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/Packages/) and [RHEL 9](https://access.redhat.com/downloads/content/python3-pip/noarch/package-latest).

**Comment by MattMatheus** [comment]
I will open an issue against the awx repo given your analysis of the root cause matches my thoughts.
