### ISSUE TITLE
SSL Termination at Load Balancer

### ISSUE THREAD

**Issue by billett83** [ansible/tower-operator#150]
I'm running into an issue whereby I'm terminating SSL at the Load balancer level. This is causing 400 Bad Request errors during CallBacks from newly provisioned servers.

Reading through the Ansible documentation (https://docs.ansible.com/ansible-tower/3.8.2/html/installandreference/proxy-support.html#ir-proxy-support) It advises the following:

```
If using SSL termination at the load balancer and forwarding traffic to a different port on the tower node (443 -> 80), set the following values in the /etc/tower/conf.d/custom.py file accordingly:

USE_X_FORWARDED_PORT = True
USE_X_FORWARDED_HOST = True
```

Is there a current method to get these parameters into the running POD during the deployment process?

**Comment by Spredzy** [comment]
`USE_X_FORWARDED_PORT = True` is set here https://github.com/ansible/awx-operator/blob/devel/roles/installer/templates/tower_config.yaml.j2#L85 - but no, there is no mechanism to specify it at that point.

In order to provide more flexibility, and not have to support each and every possible config from an operator perspective, I think we should provide a way for the user to provide a settings configmap, where user would be able to add customization one needs. (If something overwrite default config in user ConfigMap, then it should take precedence)

What would you think of such an approach @billett83 ?

**Comment by billett83** [comment]
Thank you @Spredzy . I did come across this one setting whilst trawling through the POD yesterday.

Yes, this approach sounds feasible

**Comment by Spredzy** [comment]
@tchellomello something you are interested working on ? If not let me know andd I'll assign myself.

**Comment by tchellomello** [comment]
@Spredzy yes, I'll work on it

**Comment by tchellomello** [comment]
@Spredzy, @gamuniz and I spoke today to provide a `custom.py` to override the configmap and allow users to modify it. Originally his suggestion was for `insigths*` but it can be extended for any option pretty much. Since he already started working on this PR, @gamuniz++ will submit the PR

**Comment by shanemcd** [comment]
@Spredzy @tchellomello @gamuniz Opened up https://github.com/ansible/awx-operator/issues/175 to capture the last part of this thread.

**Comment by tchellomello** [comment]
Closing this as it was documented on PR https://github.com/ansible/awx-operator/pull/214
