### ISSUE TITLE
AWXMeshIngress example uses incorrect Traefik API

### ISSUE THREAD

**Issue by whitej6** [ansible/tower-operator#1742]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Documented example 

### AWX Operator version

Latest

### AWX version

Latest

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.28.6

### Modifications

no

### Steps to reproduce

Simple new install of eks or k3s using traefik ingress controller, deploy example AWXMeshIngress for traefik

### Expected results

IngressRouteTCP object created

### Actual results

Fails to create

### Additional information

Swapping to `traefik.containo.us/v1alpha1` API works

### Operator Logs

no kube events

**Comment by kurokobo** [comment]
@whitej6 
Hi, thanks for filling the issue.

This is intended, since `traefik.containo.us` is deprecated since Traefik v2.10. Refer to the Traefik docs.

> In v2.10, the Kubernetes CRDs API Group traefik.containo.us is deprecated, and its support will end starting with Traefik v3. Please use the API Group traefik.io instead.
> https://doc.traefik.io/traefik/migration/v2/#v210

Operator has the permission to handle both `traefik.containo.us` and `traefik.io` (I made so), but as documented, `traefik.io` should be used.

https://github.com/ansible/awx-operator/blob/d0827ba42680f42ed7d0ddbe1c751e376dd3e4c4/config/rbac/role.yaml#L127-L129

If you can't see any ingressroutetcp resources even Operator reports no error, try `kubectl get` for `ingressroutetcp.traefik.io`.

```bash
$ kubectl -n awx get ingressroutetcp.traefik.io
NAME                                       AGE
ingressroutetcp.traefik.io/inbound-hop01   37s
```

For your PR, I still want to use `traefik.io` as an example, but adding notes for `traefik.containo.us` and the command `kubectl get ingressroutetcp.traefik.io` are good ideas.

**Comment by whitej6** [comment]
I'll try reverting and the get with the api part. If that works, thoughts me swapping my PR to add a note?

**Comment by kurokobo** [comment]
> thoughts me swapping my PR to add a note?

If you have the time and interest, by all means 😃
If not, I'll do that as an author of that documentation. Indeed the current documentation is a bit unfriendly.

**Comment by fosterseth** [comment]
@kurokobo thanks, feel free to close this issue once you are able to make that doc change

**Comment by kurokobo** [comment]
@fosterseth 
Thanks, PR #1757 is ready to review!
