### ISSUE TITLE
awx-operator container not available in quay.io

### ISSUE THREAD

**Issue by crouthamela** [ansible/tower-operator#190]
The container version 0.8.0 is missing from quay.io, causing an ErrImagePull right now.

https://quay.io/repository/ansible/awx-operator?tag=0.8.0&tab=tags

**Comment by lemmy04** [comment]
I'm stuck at that too.

**Comment by DANic-git** [comment]
The same
```
Failed to pull image "quay.io/ansible/awx-operator:0.8.0": rpc error: code = Unknown desc = Error response from daemon: manifest for quay.io/ansible/awx-operator:0.8.0 not found: manifest unknown: manifest unknown
```

**Comment by JouBr0** [comment]
I solved this issue by downloading the awx-operator.yaml file and change the quay.io link to quay.io/ansible/awx-operator:devel instead of quay.io/ansible/awx-operator:0.8.0
Save it local and apply this file instead of submitting the link. After that you will be able to follow the usual instructions.

**Comment by shanemcd** [comment]
Oops. Sorry folks. This has been addressed. I'll automate the problem so I don't forget next time.
