### ISSUE TITLE
Switch to using k8s_exec module instead of shell module + kubectl

### ISSUE THREAD

**Issue by tima** [ansible/tower-operator#3]
Filing this issue to keep tabs on [this issue](https://github.com/geerlingguy/tower-operator/issues/8). The use of `shell` when a module exists makes me sad.

**Comment by geerlingguy** [comment]
Since the `k8s_exec` module is now part of the `community.kubernetes` collection (which, I believe, is installed with Operator SDK when using an Ansible operator), we should be able to call it from the role.

We would just need to switch each of the tasks in the role's `main.yml` to use `k8s_exec` instead of `shell` + `kubectl` wherever that usage exists.

This was not easy to do initially because the Ansible wrapper in Go uses an HTTP proxy layer over the Kubernetes API that didn't pass through the `exec` calls correctly, but as of the resolution of https://github.com/operator-framework/operator-sdk/issues/2204, that was fixed.

The other nice thing is that allows us to drop these lines from the Dockerfile: https://github.com/ansible/awx-operator/blob/devel/build/Dockerfile#L3-L4
