### ISSUE TITLE
cr format

### ISSUE THREAD

**Issue by macthev** [ansible/tower-operator#343]
##### ISSUE TYPE
 - Doco Bug Report

##### ENVIRONMENT
* AWX version:19.1.0
* Operator version: latest
* Kubernetes version:  1.21
* AWX install method: kubernetes
##### STEPS TO REPRODUCE

Following the doco to add loadbalancer(or any mods in the main doco), instructions say

spec:
    ingress_type: LoadBalancer
    loadbalancer_protocol: http

But get verification error.

Actually needs to be something like will pass validation(but not work during deployment ansible saying tower_ unknown.

Seems there a mismatch with doco and actual.

spec:
    tower_ingress_type: LoadBalancer

So do they need tower_ prefix?

##### ACTUAL RESULTS

ValidationError(AWX.spec): unknown field "ingress_type" in com.ansible.awx.v1beta1.AWX.spec

**Comment by tchellomello** [comment]
@cr if you are getting this error it's because you are running the version `0.9.0` therefore please follow the documentation at https://github.com/ansible/awx-operator/tree/0.9.0 which matches that particular branch. 

The change you mentioned is https://github.com/ansible/awx-operator/pull/331 and will be present on the next released version.

**Comment by macthev** [comment]
Thank you, yes make sense now.
