### ISSUE TITLE
Persistent Volumes for projects folder

### ISSUE THREAD

**Issue by kylecurtis-od** [ansible/tower-operator#46]
If you are trying to use a persistent volume on kubernetes, and then mount it to /var/lib/awx/projects, it is a requirement to mount it to both the awx web and task containers. can we update the docs to reflect this?

**Comment by balonik** [comment]
It is currently not possible to mount persistent volume on `/var/lib/awx/projects`, because there is a hardcoded volume mount in https://github.com/ansible/awx-operator/blob/0d6980b9b4db535dec6f271bbe634ebdbc10de27/roles/installer/templates/tower_deployment.yaml.j2#L182 which uses `emptyDir` https://github.com/ansible/awx-operator/blob/0d6980b9b4db535dec6f271bbe634ebdbc10de27/roles/installer/templates/tower_deployment.yaml.j2#L252

Could you please add possibility to mount `/var/lib/awx/projects` as persistent volume?

**Comment by tchellomello** [comment]
Working on patch for it
