### ISSUE TITLE
awx-operator resets admin password after scale down of awx deployment

### ISSUE THREAD

**Issue by amtilghman** [ansible/tower-operator#484]
related: https://github.com/ansible/awx-operator/issues/477

My original issue was closed with a note to try something and if it didn't work to re-open the issue, I didn't see how to reopen the original issue so opening a new one.

I've provided the exact steps I'm performing below.
Prior to awx-operator (the docker-compose install) when I've upgraded/reinstalled AWX the admin password was always preserved and not overwritten by the installer.
As you can see in the output below some data is being preserved but the admin password is being overwritten, is this a bug or working as intended?  I could envision myself scaling down awx when preparing to power down a cluster and I would be surprised if after the cluster was turned back on to find my admin password had changed.

#This is the password set by the installer
$ kubectl get secret awx-demo-admin-password -o jsonpath="{.data.password}" | base64 --decode
G2jE1X46OfX09Va8G6FXtbXs5supqtFk

#I now login to the AWX UI and change the admin password to password

#I also create a new user called newuser and set the password to password

#I can curl the api with the admin user and it's new password
$ curl -sk -u admin:password http://awx.apps.virtual.home.arpa/api/v2/me/ | jq .results[].username
"admin"

#I can curl the api with the newuser user and it's new password
$ curl -sk -u newuser:password http://awx.apps.virtual.home.arpa/api/v2/me/ | jq .results[].username
"newuser"

#The password set by the installer does not work, this is good
$ curl -sk -u admin:G2jE1X46OfX09Va8G6FXtbXs5supqtFk http://awx.apps.virtual.home.arpa/api/v2/me/ | jq .results[].username
jq: error (at :0): Cannot iterate over null (null)

#I am running 1 replica of awx-demo and 1 replica of awx-operator
$ oc get rs
NAME DESIRED CURRENT READY AGE
awx-demo-9975db9b6 1 1 1 3d19h
awx-operator-79bc95f78 1 1 1 3d19h

#I scale down awx-demo
$ oc scale deployment --replicas=0 awx-demo
deployment.apps/awx-demo scaled

#I see awx-demo was scaled down
$ oc get rs
NAME DESIRED CURRENT READY AGE
awx-demo-9975db9b6 0 0 0 3d19h
awx-operator-79bc95f78 1 1 1 3d19h

#I see operator has restored awx-demo
$ oc get rs
NAME DESIRED CURRENT READY AGE
awx-demo-9975db9b6 1 1 1 3d19h
awx-operator-79bc95f78 1 1 1 3d19h

#The admin password I had set prior no longer works
$ curl -sk -u admin:password http://awx.apps.virtual.home.arpa/api/v2/me/ | jq .results[].username
jq: error (at :0): Cannot iterate over null (null)

#The newuser account is fine
$ curl -sk -u newuser:password http://awx.apps.virtual.home.arpa/api/v2/me/ | jq .results[].username
"newuser"

#I see the default password set by the installer has been reset
[root@lab0l00 /]# curl -sk -u admin:G2jE1X46OfX09Va8G6FXtbXs5supqtFk http://awx.apps.virtual.home.arpa/api/v2/me/ | jq .results[].username
"admin"

**Comment by tchellomello** [comment]
@amtilghman reading the code it looks that is exactly what is expected to happen. If you look at 
https://github.com/ansible/awx-operator/blob/devel/roles/installer/tasks/initialize_django.yml#L2-L26 the password will get updated for the `admin` user according to the password set in the `<resource>-admin-password`. 

Since the `awx` instance must be driven by the `operator`, operations like `scaling` or setting the `admin` password must be done via the operator. Any extra users created (like the one on your example) will remain in the database, however,  if you want to override the `admin` password, please modify the secret so whenever a new reconciliation happens, the password will remain. 

If you think this could use some clarification on our documentation, please submit a PR and we will be happy to get it merged. 

In light of this, I'm going ahead and closing this issue.
