### ISSUE TITLE
Single Tower Deployment vs Deployment Per Component

### ISSUE THREAD

**Issue by tylerauerbeck** [ansible/tower-operator#5]
In the latest release of the operator, it looks like the deployment has gone from each components having its own deployment (task, web, etc.) to all containers being inside a single pod. Was there a technical reason behind this? Seems like this would cause issues if you wanted things to scale independently of each other moving forward (i.e. only scale web due to increased traffic, etc.)

**Comment by geerlingguy** [comment]
cc @matburt — I know we discussed the reasons for everything being in the same pod and mounting sockets instead of using TCP connections; you may be better at explaining the architecture than I am.

**Comment by matburt** [comment]
On the Tower/AWX side we actually don't support that at the moment because some of the components just aren't engineered to do that. This change brings this deployment in line with our current official deployment.

Parts of this system are getting rearchitected in the future but for the moment, I want to re-use the system that we already have in the existing Tower and AWX installers.
