### ISSUE TITLE
Are finalizers fully removed?

### ISSUE THREAD

**Issue by ddevalco** [ansible/tower-operator#697]
I noticed this in the 0.10.0 release notes:

- Fully remove finalizer (Christian M. Adams) - fd92050

Yet even in 0.14.0 the roles show finalizers:

https://github.com/ansible/awx-operator/blob/devel/config/rbac/role.yaml

`    resources:
      - services/finalizers`

`resources:
      - deployments/finalizers`

I don't fully understand this stuff but I ran into questions as to why the finalizers were needed with the roles and it made me curious why they would be if the statement "fully remove finalizer" is true in the PR?

**Comment by AlanCoding** [comment]
Let me quickly ping his name on github @rooftopcellist

**Comment by rooftopcellist** [comment]
There are built in finalizers that do garbage collection based on owner references on objects. The PR you linked to and https://github.com/ansible/awx-operator/pull/299 collectively remove a finalized we previously had to remove ownerRefs from object that we didn’t want the built in k8s finalizer to remove iirc. 

As for if those rules are still needed on the ServiceAccount for the operator, I am not sure off hand. They should likely be removed. But we should test deploying without those rules, deleting the AWX CR, then observing that the child objects get cleaned up (PVC’s and generated secrets are expected to remain because their ownerRef’s have been explicitly removed).

**Comment by shanemcd** [comment]
It looks like that changelog message was a little confusing. It seems like we just removed our custom finalizer.
