### ISSUE TITLE
Operator image not published?

### ISSUE THREAD

**Issue by mamercad** [ansible/tower-operator#7]
I don't see the ansible/tower-operator image published on Docker Hub.

https://github.com/ansible/awx-operator/blob/90fa14345355614043da4f9c87a6a7ac778f8774/build/chain-operator-files.yml#L9

**Comment by geerlingguy** [comment]
It looks like @matburt just published a new operator image at `ansible/awx-operator` (https://hub.docker.com/r/ansible/awx-operator) a few hours ago. The old image should still be there maybe for some amount of time just so that people with existing installs don't get image pull errors though... otherwise the operator will break for any existing installs.

The new code of this operator is here: https://github.com/ansible/awx-operator/pull/4 (not yet merged).

**Comment by jcomito** [comment]
@geerlingguy Hi Sir! Appears that there isn't the new ansible/awx-operator or ansible/tower-operator images published on DockerHub. I'm getting image pull errors for both. Not able to build the old or (this) new project. Looking forward to this!!

**Comment by mamercad** [comment]
```
❯ docker pull ansible/awx-operator:0.4.0
0.4.0: Pulling from ansible/awx-operator
ee2244abc66f: Pull complete
befb03b11956: Pull complete
9d05b535e611: Pull complete
51a84b8e6e04: Pull complete
1730fea3a412: Pull complete
a7518fc4b4b8: Pull complete
96917d26f5e1: Pull complete
a5236a9afd95: Pull complete
45b98e5f36b9: Pull complete
04b6be6adfba: Pull complete
763daf606152: Pull complete
5c188bd06a4e: Pull complete
ad63164a669e: Pull complete
2c6dc4c13382: Pull complete
d35e54cd610a: Pull complete
Digest: sha256:0a4f7a5143a2616cdaf2bb3824f36efa6cc41c4e82f3bee96e72c6aa837e64b0
Status: Downloaded newer image for ansible/awx-operator:0.4.0
docker.io/ansible/awx-operator:0.4.0
