### ISSUE TITLE
awx-postgres-configuration secret doesn't get created with custom postgres settings

### ISSUE THREAD

**Issue by kaushik4r** [ansible/tower-operator#884]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After deploying the awx-operator, the "awx-postgres-configuration" secret doesn't get created with custom postgres settings(even though it was mentioned in posgtes_secret.yaml.j2). The secret gets created with the default settings and _**type**_ set as **_managed_** instead of **_unmanaged_**. As a result the awx-operator tries to create a managed postgres instance(which shouldn't be the case).

##### ENVIRONMENT
* AWX version: 20.0.0
* Operator version: 0.18.0
* Kubernetes version: 1.21.0
* AWX install method: Kubernetes

##### STEPS TO REPRODUCE
Configure the below settings in postgres_secret.yaml.j2:
`---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ ansible_operator_meta.name }}-postgres-configuration'
  namespace: 'ansible-awx'
  labels:
    app.kubernetes.io/name: '{{ ansible_operator_meta.name }}'
    app.kubernetes.io/part-of: '{{ ansible_operator_meta.name }}'
    app.kubernetes.io/managed-by: '{{ deployment_type }}-operator'
    app.kubernetes.io/component: '{{ deployment_type }}'
    app.kubernetes.io/operator-version: '{{ lookup("env", "OPERATOR_VERSION") }}'
stringData:
  password: awxpass
  username: awx
  database: awx
  port: 5432
  host: x.x.x.x
  sslmode: prefer
  type: unmanaged
type: Opaque`

##### EXPECTED RESULTS
$ kubectl get secret awx-postgres-configuration -o jsonpath="{.data.type}" -n ansible-awx | base64 --decode
unmanaged

##### ACTUAL RESULTS

$ kubectl get secret awx-postgres-configuration -o jsonpath="{.data.type}" -n ansible-awx | base64 --decode
managed

##### ADDITIONAL INFORMATION

Due to this reason, the awx-operator tries to create a managed postgres instance instead of using the external postgres instance.

**Comment by rooftopcellist** [comment]
@kaushik4r Can you please share your AWX spec?  My guess is that you are trying to specify the variables you see in the `roles/installer/templates/postgres_secret.yaml.j2` directly on the `spec` for the AWX CR.  If that is the case, this will not work.  The purpose of that `postgres_secret.yaml.j2` file is to generate a secret if one is not supplied.  

If you are trying to configure an external database instead of use the managed postgresql pod, then you need to pre-create that secret on in the namespace you intend to deploy to, then specify that secret on the spec, like this:

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  postgres_configuration_secret: <name-of-your-secret>
```
These are the docs on how to do that - https://github.com/ansible/awx-operator/blob/devel/README.md#external-postgresql-service

I put up a patch to try to clarify this in the docs - https://github.com/ansible/awx-operator/pull/895

**Comment by kaushik4r** [comment]
@rooftopcellist I was using the later approach mentioned in the highlighted portion below -

![image](https://user-images.githubusercontent.com/14088417/166054951-67d1c469-0f37-4f5a-b586-161e3e64364b.png)

Therefore, directly updated `postgres_secret.yaml.j2` file with the external postgres details. This is the only file where I made changes. Please suggest if I need change any other files.

**Comment by rooftopcellist** [comment]
@kaushik4r what I meant by that line was that the operator is smart enough to look for an existing secret by the name of `<your-awx-cr-name>-postgres-configuration` if it has been pre-created in the namespace.  Not that the operator files itself should be edited.  

I realize this was unclear, so in the PR I linked above, I removed that line completely.

**Comment by rooftopcellist** [comment]
@kaushik4r thank you for your feedback and for bring this up.  The docs PR has merged, so I will go ahead an close this issue for now.
