### ISSUE TITLE
Live/Readyness checks for awx-web & awx-task

### ISSUE THREAD

**Issue by moonrail** [ansible/tower-operator#926]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Current deployment does not include any `livenessProbes` or `readinessProbes` for the containers.

This leads to issues with the Deployment, as it just replaces all pods nearly at the same time and does not wait, until an exchanged pod is ready yet. Therefore AWX may not be reachable temporarily.

This is especially problematic if the user added a configuration error via any of the AWX-options, such as extra-config/custom.py or database-config.

##### ENVIRONMENT
* AWX version: 21.0.0
* Operator version: 0.21.0
* Kubernetes version: 1.22.9
* AWX install method: Kubernetes via awx-operator

##### STEPS TO REPRODUCE
* deploy awx-operator & AWX as described in README.md
* verify, that AWX works
* change configuration of AWX resource
* wait for awx-operator to apply new deployment

##### EXPECTED RESULTS
* K8s deployment gracefully stops each pod and deploys another one sequentially, without downtime

##### ACTUAL RESULTS
* K8s deployment stops each pod nearly at the same time, as new pods are marked as ready even when they are not yet
* a downtime can be experienced

**Comment by djyasin** [comment]
@TheRealHaoLiu and I worked together to test this as follows:

- Verified that init container was successfully added to controller deployment

- Init container ran successfully and performed database migration on first run
- Verified that all 4 of the controller containers eventually got to “running” state after init container finish execution 
- Validated that Controller UI is functional and able to log in 
- Sniff test: project sync and demo job runs successfully
- When pod is deleted migration does not get run and exits gracefully and recreated by kube  migration run and exits gracefully
- We scaled down awx-operator and manually scaled up the controller deployment to 5 and observed that the instances of the controller pod initialized serially (due to database lock) and eventually all 5 instance of controller pod got to an running state with no issue

> 
[Lyasin@paws-itive awx-operator]$ oc logs -f example-7c4db9b87d-9xcv8 -c database-migration                                                                   │···························································
Operations to perform:                                                                                                                                        │···························································
  Apply all migrations: auth, conf, contenttypes, main, oauth2_provider, sessions, sites, social_django, sso, taggit                                          │···························································
Running migrations:                                                                                                                                           │···························································
  No migrations to apply.

**Comment by kdelee** [comment]
@djyasin @TheRealHaoLiu given you testing can you approve the PR?

**Comment by rooftopcellist** [comment]
This was implemented and merged here:
* https://github.com/ansible/awx-operator/pull/1674

Please check it out!
