### ISSUE TITLE
AWX operator not deploying postgres DB in default postgres pod

### ISSUE THREAD

**Issue by jompins** [ansible/tower-operator#949]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### AWX Operator version

19.5

### AWX version

19.5

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.23.4+k3s1

### Modifications

yes

### Steps to reproduce

Deploy an air gaped install of AWX with the operator and the following settings from a private registry. 

> ---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  service_type: nodeport
  image: SERVERNAME/ansible/awx
  image_version: latest
  image_pull_policy: Always
  control_plane_ee_image: SERVERNAME/ansible/awx-ee:latest
  postgres_image: SERVERNAME/ansible/postgres
  postgres_image_version: v12
  redis_image: SERVERNAME/ansible/redis
  redis_image_version: latest
  init_container_image: SERVERNAME/ansible/centos
  init_container_image_version: stream8
  ee_images:
    - name: awx
      image: SERVERNAME/ansible/awx-ee:latest

### Expected results

AWX is available with a fresh install and the default postgres database and some demo data. 

### Actual results

All pods deploy fine but process gets hung hup on "waiting for db migration" even though the setup is freshly deployed. Postgrescontainer logs show that the service is properly spinning up. awx-web/awx-task etc. show that they can not connect to the postgres DB. 

awx-manage migrate --no-input shows this error: 
`a펵wbash-5.1$awx-manage migrate --no-input
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: No route to host
        Is the server running on host "awx-postgres" (10.42.0.223) and accepting
        TCP/IP connections on port 5432?`

It appears that there is no database residing in the postgresdb.

**Comment by rooftopcellist** [comment]
I expect this is failing because the init container's image and image version cannot be pulled.  If you describe the pods in the namespace you deployed to, do you see an imgPullError on an init container?  Or the postgres container?  

```
kubectl get pods -n <namespace>
```

Also, what is the awx-operator version you are using? or branch?


We use `centos:stream8` for the postgres init container to check for an data dir issue from a previous release and remediate it if needed ([here](https://github.com/ansible/awx-operator/commit/12a58d71fbf0b29874f8bff235e360c471dc6b8c#diff-10704417212a97d163eb17e754cd50318b239a3da81cd54e04f8c510168a278eR132-R134)).

My guess is that there is an issue pulling that init image, or potentially pulling the postgres image.  I don't know how you've tagged the postgres image on your registry, but usually the tag would be `12`, not `v12`.

**Comment by jompins** [comment]
This issue was related to container.d issues. Switching back to legac iptables instead of nftables solved the problem
